# deploy/docker-compose.yml

version: '3.8'

services:
  fintrix_laravel:
    restart: unless-stopped
    container_name: fintrix_app
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    # allocate as many volumes as necessary, if needed.
    volumes:
      - ../storage/app:/var/www/html/storage/app
      - ../:/var/www/html/
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_VERSION: ${APP_VERSION}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: fintrix_database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    ports:
      - "8082:80"
    networks:
      - n-laravel
    depends_on:
      - fintrix_database

  fintrix_database:
    restart: unless-stopped
    container_name: codetrix_db 
    image: mariadb:lts-jammy
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - n-laravel
    ports:
      - "3306:3306"

  # fintrix_phpmyadmin:
  #   restart: unless-stopped
  #   container_name: fintrix_phpmyadmin
  #   image: phpmyadmin:latest
  #   environment:
  #     PMA_HOST: fintrix_database
  #     PMA_USER: ${DB_USERNAME}
  #     PMA_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "8083:80"
  #   networks:
  #     - n-laravel
  #   depends_on:
  #     - fintrix_database

volumes:
  v-database:


networks:
  n-laravel:
    driver: bridge